### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by the-tatanka** [Lerer/veracode-sca#19]
I would love this feature, but I cannot get it running.

My repo: https://github.com/the-tatanka/tractusx
Action: https://github.com/the-tatanka/tractusx/blob/main/.github/workflows/veracode-issues.yml
Example run: https://github.com/the-tatanka/tractusx/runs/5413186112?check_suite_focus=true

Error message: "spawnSync /bin/sh ENOBUFS"

I also looked through the other repos that use this feature - the current version doesn't seem to work in any repo.

The feature is really nice, because then you don't have to give all users permissions to Veracode.
And the Advanced Sec features are not needed.

**Comment by Lerer** [comment]
@the-tatanka ,
Please try again with version v1.0.7

I tested locally with your project and it worked.

It need to be tested by you to close the isseu

**Comment by the-tatanka** [comment]
v1.0.7 works!
Thank you very much.
