### ISSUE TITLE
Duplicate issues

### ISSUE THREAD

**Issue by the-tatanka** [Lerer/veracode-sca#21]
![image](https://user-images.githubusercontent.com/59142915/157524185-c00d770b-3eea-487a-b620-ce278750d9d0.png)

With each additional pipeline run, the same issues are created if they have not been resolved. 
This floods the issues with duplicates.

I think this is not intended.

**Comment by Lerer** [comment]
@the-tatanka,
Are you using GitHub online, or Enterprise (cloud or server)?

**Comment by the-tatanka** [comment]
GitHub online

**Comment by Lerer** [comment]
@the-tatanka ,
Please try v1.0.8

There was a problem with the query to pull existing issues from GitHub. The specific problem resolved and tested (by me).

Please let me know if it also solve your problem.

**Comment by the-tatanka** [comment]
This solved my problem.
Thank you :)
